In [1]:
import numpy as np
rng = np.random.default_rng()
rng.integers(1,11,size = (3,3))

array([[ 4,  7,  6],
       [ 2,  6, 10],
       [ 8,  7,  8]])

In [2]:
import numpy as np
rng = np.random.default_rng(seed = 1)       #seed = 1 means fixed the random numbers
rng.integers(1,11,size = (3,3))

array([[ 5,  6,  8],
       [10,  1,  2],
       [ 9, 10,  3]])

In [3]:
import numpy as np
rng = np.random.uniform(1,11,size = (3,3)) #uniform means random numbers with floating point numbers
rng

array([[ 8.36383572,  8.49173635,  1.66342543],
       [ 3.40479473,  5.33920045,  1.49023148],
       [10.32625769,  1.03283767,  4.78858714]])

In [4]:
import numpy as np
rng = np.random.default_rng()
array = np.array([[1,2,3],
                [4,5,6]])
rng.shuffle(array)
array

array([[4, 5, 6],
       [1, 2, 3]])

In [6]:
import numpy as np
rng = np.random.default_rng()
array = np.array([["Apple","Orange"],
                ["Banana","Pineapple"]])
array2 = rng.choice(array,size = 3)
array2

array([['Banana', 'Pineapple'],
       ['Apple', 'Orange'],
       ['Banana', 'Pineapple']], dtype='<U9')

Creat a random value with null value

In [ ]:
import numpy as np
data = np.random.rand(5,5)
for col in range(data.shape[1]) :
    null_indicate = np.random.choice(data.shape[0],3,replace=False)
    data[null_indicate,col] = np.nan

data


array([[       nan, 0.41867026,        nan, 0.21774473,        nan],
       [0.51671864,        nan, 0.74568725,        nan,        nan],
       [       nan,        nan,        nan,        nan, 0.69116225],
       [       nan,        nan, 0.33072674,        nan, 0.46434694],
       [0.35917516, 0.07876079,        nan, 0.11426319,        nan]])